name: geosfera
description: "A Geo Guesser Game."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  country_flags: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - data/country_list.txt
    - data/country_data.txt
    - data/logo/geosfera_logo_bgx.png
    - data/lottie/correct.json
    - data/lottie/incorrect.json
    - data/map/africa/ae/vector.svg
    - data/map/africa/ao/vector.svg
    - data/map/africa/bf/vector.svg
    - data/map/africa/bi/vector.svg
    - data/map/africa/bj/vector.svg
    - data/map/africa/bw/vector.svg
    - data/map/africa/cd/vector.svg
    - data/map/africa/cf/vector.svg
    - data/map/africa/cg/vector.svg
    - data/map/africa/ci/vector.svg
    - data/map/africa/cm/vector.svg
    - data/map/africa/cv/vector.svg
    - data/map/africa/dj/vector.svg
    - data/map/africa/dz/vector.svg
    - data/map/africa/eg/vector.svg
    - data/map/africa/eh/vector.svg
    - data/map/africa/er/vector.svg
    - data/map/africa/et/vector.svg
    - data/map/africa/ga/vector.svg
    - data/map/africa/gh/vector.svg
    - data/map/africa/gm/vector.svg
    - data/map/africa/gn/vector.svg
    - data/map/africa/gq/vector.svg
    - data/map/africa/gw/vector.svg
    - data/map/africa/ke/vector.svg
    - data/map/africa/km/vector.svg
    - data/map/africa/lr/vector.svg
    - data/map/africa/ls/vector.svg
    - data/map/africa/ly/vector.svg
    - data/map/africa/ma/vector.svg
    - data/map/africa/mg/vector.svg
    - data/map/africa/ml/vector.svg
    - data/map/africa/mr/vector.svg
    - data/map/africa/mu/vector.svg
    - data/map/africa/mw/vector.svg
    - data/map/africa/mz/vector.svg
    - data/map/africa/na/vector.svg
    - data/map/africa/ne/vector.svg
    - data/map/africa/ng/vector.svg
    - data/map/africa/re/vector.svg
    - data/map/africa/rw/vector.svg
    - data/map/africa/sc/vector.svg
    - data/map/africa/sd/vector.svg
    - data/map/africa/sh/vector.svg
    - data/map/africa/sl/vector.svg
    - data/map/africa/sn/vector.svg
    - data/map/africa/so/vector.svg
    - data/map/africa/ss/vector.svg
    - data/map/africa/st/vector.svg
    - data/map/africa/sz/vector.svg
    - data/map/africa/td/vector.svg
    - data/map/africa/tg/vector.svg
    - data/map/africa/tn/vector.svg
    - data/map/africa/tz/vector.svg
    - data/map/africa/ug/vector.svg
    - data/map/africa/yt/vector.svg
    - data/map/africa/za/vector.svg
    - data/map/africa/zm/vector.svg
    - data/map/africa/zw/vector.svg
    - data/map/asia/af/vector.svg
    - data/map/asia/am/vector.svg
    - data/map/asia/aq/vector.svg
    - data/map/asia/az/vector.svg
    - data/map/asia/bd/vector.svg
    - data/map/asia/bh/vector.svg
    - data/map/asia/bn/vector.svg
    - data/map/asia/bt/vector.svg
    - data/map/asia/bv/vector.svg
    - data/map/asia/cc/vector.svg
    - data/map/asia/cn/vector.svg
    - data/map/asia/cx/vector.svg
    - data/map/asia/cy/vector.svg
    - data/map/asia/ge/vector.svg
    - data/map/asia/gs/vector.svg
    - data/map/asia/hk/vector.svg
    - data/map/asia/hm/vector.svg
    - data/map/asia/id/vector.svg
    - data/map/asia/il/vector.svg
    - data/map/asia/in/vector.svg
    - data/map/asia/io/vector.svg
    - data/map/asia/iq/vector.svg
    - data/map/asia/ir/vector.svg
    - data/map/asia/jo/vector.svg
    - data/map/asia/jp/vector.svg
    - data/map/asia/kg/vector.svg
    - data/map/asia/kh/vector.svg
    - data/map/asia/kp/vector.svg
    - data/map/asia/kr/vector.svg
    - data/map/asia/kw/vector.svg
    - data/map/asia/kz/vector.svg
    - data/map/asia/la/vector.svg
    - data/map/asia/lb/vector.svg
    - data/map/asia/lk/vector.svg
    - data/map/asia/mm/vector.svg
    - data/map/asia/mn/vector.svg
    - data/map/asia/mo/vector.svg
    - data/map/asia/mv/vector.svg
    - data/map/asia/my/vector.svg
    - data/map/asia/nc/vector.svg
    - data/map/asia/np/vector.svg
    - data/map/asia/om/vector.svg
    - data/map/asia/ph/vector.svg
    - data/map/asia/pk/vector.svg
    - data/map/asia/qa/vector.svg
    - data/map/asia/ru/vector.svg
    - data/map/asia/sa/vector.svg
    - data/map/asia/sg/vector.svg
    - data/map/asia/sr/vector.svg
    - data/map/asia/sy/vector.svg
    - data/map/asia/tf/vector.svg
    - data/map/asia/th/vector.svg
    - data/map/asia/tj/vector.svg
    - data/map/asia/tl/vector.svg
    - data/map/asia/tm/vector.svg
    - data/map/asia/tr/vector.svg
    - data/map/asia/tw/vector.svg
    - data/map/asia/uz/vector.svg
    - data/map/asia/vn/vector.svg
    - data/map/asia/ye/vector.svg
    - data/map/europe/ad/vector.svg
    - data/map/europe/al/vector.svg
    - data/map/europe/at/vector.svg
    - data/map/europe/ax/vector.svg
    - data/map/europe/ba/vector.svg
    - data/map/europe/be/vector.svg
    - data/map/europe/bg/vector.svg
    - data/map/europe/by/vector.svg
    - data/map/europe/ch/vector.svg
    - data/map/europe/cz/vector.svg
    - data/map/europe/de/vector.svg
    - data/map/europe/dk/vector.svg
    - data/map/europe/ee/vector.svg
    - data/map/europe/es/vector.svg
    - data/map/europe/fi/vector.svg
    - data/map/europe/fo/vector.svg
    - data/map/europe/fr/vector.svg
    - data/map/europe/gb/vector.svg
    - data/map/europe/gg/vector.svg
    - data/map/europe/gi/vector.svg
    - data/map/europe/gr/vector.svg
    - data/map/europe/hr/vector.svg
    - data/map/europe/hu/vector.svg
    - data/map/europe/ie/vector.svg
    - data/map/europe/im/vector.svg
    - data/map/europe/is/vector.svg
    - data/map/europe/it/vector.svg
    - data/map/europe/li/vector.svg
    - data/map/europe/lt/vector.svg
    - data/map/europe/lu/vector.svg
    - data/map/europe/lv/vector.svg
    - data/map/europe/mc/vector.svg
    - data/map/europe/md/vector.svg
    - data/map/europe/me/vector.svg
    - data/map/europe/mk/vector.svg
    - data/map/europe/mt/vector.svg
    - data/map/europe/nl/vector.svg
    - data/map/europe/no/vector.svg
    - data/map/europe/pl/vector.svg
    - data/map/europe/pt/vector.svg
    - data/map/europe/ro/vector.svg
    - data/map/europe/rs/vector.svg
    - data/map/europe/se/vector.svg
    - data/map/europe/si/vector.svg
    - data/map/europe/sj/vector.svg
    - data/map/europe/sk/vector.svg
    - data/map/europe/sm/vector.svg
    - data/map/europe/ua/vector.svg
    - data/map/europe/va/vector.svg
    - data/map/namerica/ag/vector.svg
    - data/map/namerica/ai/vector.svg
    - data/map/namerica/aw/vector.svg
    - data/map/namerica/bb/vector.svg
    - data/map/namerica/bl/vector.svg
    - data/map/namerica/bm/vector.svg
    - data/map/namerica/bq/vector.svg
    - data/map/namerica/bs/vector.svg
    - data/map/namerica/bz/vector.svg
    - data/map/namerica/ca/vector.svg
    - data/map/namerica/cr/vector.svg
    - data/map/namerica/cu/vector.svg
    - data/map/namerica/cw/vector.svg
    - data/map/namerica/dm/vector.svg
    - data/map/namerica/do/vector.svg
    - data/map/namerica/gd/vector.svg
    - data/map/namerica/gl/vector.svg
    - data/map/namerica/gp/vector.svg
    - data/map/namerica/gt/vector.svg
    - data/map/namerica/hn/vector.svg
    - data/map/namerica/ht/vector.svg
    - data/map/namerica/jm/vector.svg
    - data/map/namerica/kn/vector.svg
    - data/map/namerica/ky/vector.svg
    - data/map/namerica/lc/vector.svg
    - data/map/namerica/mf/vector.svg
    - data/map/namerica/mq/vector.svg
    - data/map/namerica/ms/vector.svg
    - data/map/namerica/mx/vector.svg
    - data/map/namerica/pa/vector.svg
    - data/map/namerica/pm/vector.svg
    - data/map/namerica/pr/vector.svg
    - data/map/namerica/sv/vector.svg
    - data/map/namerica/sx/vector.svg
    - data/map/namerica/tc/vector.svg
    - data/map/namerica/tt/vector.svg
    - data/map/namerica/us/vector.svg
    - data/map/namerica/vc/vector.svg
    - data/map/namerica/vg/vector.svg
    - data/map/namerica/vi/vector.svg
    - data/map/oceania/as/vector.svg
    - data/map/oceania/au/vector.svg
    - data/map/oceania/ck/vector.svg
    - data/map/oceania/fj/vector.svg
    - data/map/oceania/gu/vector.svg
    - data/map/oceania/ki/vector.svg
    - data/map/oceania/nf/vector.svg
    - data/map/oceania/nr/vector.svg
    - data/map/oceania/nu/vector.svg
    - data/map/oceania/nz/vector.svg
    - data/map/oceania/pf/vector.svg
    - data/map/oceania/pg/vector.svg
    - data/map/oceania/pn/vector.svg
    - data/map/oceania/pw/vector.svg
    - data/map/oceania/sb/vector.svg
    - data/map/oceania/tk/vector.svg
    - data/map/oceania/to/vector.svg
    - data/map/oceania/vu/vector.svg
    - data/map/oceania/wf/vector.svg
    - data/map/oceania/ws/vector.svg
    - data/map/samerica/ar/vector.svg
    - data/map/samerica/bo/vector.svg
    - data/map/samerica/br/vector.svg
    - data/map/samerica/cl/vector.svg
    - data/map/samerica/co/vector.svg
    - data/map/samerica/ec/vector.svg
    - data/map/samerica/fk/vector.svg
    - data/map/samerica/gf/vector.svg
    - data/map/samerica/gy/vector.svg
    - data/map/samerica/ni/vector.svg
    - data/map/samerica/pe/vector.svg
    - data/map/samerica/py/vector.svg
    - data/map/samerica/uy/vector.svg
    - data/map/samerica/ve/vector.svg
